Use task for applying flags to all engines
ngld/old-knossos pull request #131
Opened 2018-07-16 16:31 UTC by asarium

For me the "Apply to all" button causes the main window to become
unresponsive since I have a lot of engine versions installed. Knossos
retrieves the flags in the main thread so until all engine versions have
been checked, the main window becomes unresponsive.

This fixes that by using a background task for retrieving the engine
flags which minimizes the work that is done on the main thread.

This currently does not display a progress bar in the GUI since I don't
know how to enable that for my task. How can I enable that?

2018-07-16 18:19 UTC, ngld requested changes

2018-07-16 18:19 UTC, ngld commented on knossos/tasks.py
> +        self.mods = mods
`self.mods` tells Knossos to display the progress bar on these mods. If you want a progress bar on the bottom, you need to leave it empty.

2018-07-16 18:19 UTC, ngld commented on knossos/tasks.py
> +            self.add_work((mod,))
`self.add_work` accepts a list of items. Just pass `mods` to it.

2018-07-16 18:19 UTC, ngld commented on knossos/tasks.py
> +            progress.start_task(0.0, 1.0, 'Applying to {} {}'.format(mod.mid, mod.version))
`start_task` / `finish_task` are used for nesting. To actually update the progress bar, you need to call `progress.update`. The progress message wouldn't be visible in this case since the progress bar only shows the task's title and no detailed view for this type of task has been implemented.

You don't actually need the progress functions since you don't update the progress within one work item and progress based on the amount of processed items is automatically handled by `Task`.
TL;DR: Remove the `progress.start_task` and `progress.finish_task` calls.

2018-07-16 18:19 UTC, ngld commented on knossos/tasks.py
> +class ApplyEngineFlagsTaks(progress.Task):
Typo

2018-07-16 20:36 UTC, asarium commented on knossos/tasks.py
> +        self.mods = mods
Ah, good to know. I didn't even need that attribute and after I removed it the progress bar shows up.

One thing I noticed was that the progress bar always seems to show 0% even for other tasks. Is that intentional or some kind of bug?

2018-07-16 20:37 UTC, asarium commented on knossos/tasks.py
> +            self.add_work((mod,))
Ah, I thought i needed tuples but this is a lot cleaner.

2018-07-16 20:37 UTC, asarium commented on knossos/tasks.py
> +            progress.start_task(0.0, 1.0, 'Applying to {} {}'.format(mod.mid, mod.version))
Yes, I was a little confused about how the progress system works. I removed all usages of those functions from the task code now.

2018-07-16 20:38 UTC, asarium commented on knossos/tasks.py
> +class ApplyEngineFlagsTaks(progress.Task):
Fixed.

2018-07-17 23:02 UTC, ngld commented
The progress bar should be working. Does it move if you check the file integrity of a mod with a bunch of packages?
You can also add `progress.update(0, '')` at the start of your `work` method and see if that helps.

2018-07-18 07:47 UTC, asarium commented
So, checking the file integrity does show the progress bar properly but `progress.update(0, '')` doesn't seem to do anything. However, if I add the progress update and set `_threads` to 1 it works correctly. Without the `progress.update(0, '')` the progress bar still stays at 0%.

Final try: I added a random sleep time to each work call and now the progress bar also works "correctly". Maybe the tasks are done before the progress bar is updated? But then it still shows up for a short time and stays at 0%...

Anyway, it seems to be working when I add the `progress.update(0, '')` so this should be ready now.

2018-07-24 13:27 UTC, merged