Revise post-setup retail install prompt
ngld/old-knossos pull request #147
Opened 2018-12-11 06:38 UTC by jg18

Improve UX of the post-setup retail install process.

P.S. I think I'm getting the hang of this! 😁

P.P.S. Although I added the `inline-button` class to the Browse... button which is from my "revise welcome page" PR #145 . I also couldn't get the `inline-button` class to work when I tried to adapt something from the other PR, presumably something to do with some other CSS rules overriding it, but I don't know what 😠

2018-12-11 06:43 UTC, jg18 commented
Also the formatting is a little hackish with respect to bootstrap classes and use of HTML paragraphs, hoping you can help me with tthat.

2018-12-11 06:50 UTC, jg18 commented on html/templates/kn-page.vue
> +                        <button class="btn btn-primary" @click="finishRetailPrompt">Continue</button>
Does this `@click` also require the `.prevent` ? Just noticed it isn't there.

2018-12-13 21:17 UTC, ngld commented on html/templates/kn-page.vue
> +                        <button class="btn btn-primary" @click="finishRetailPrompt">Continue</button>
In most cases the `.prevent` is unnecessary. IIRC the only places it's really required are: Links and buttons inside `<form>`s with an `action` attribute. That said... I'm a bit paranoid and using it doesn't hurt.

2018-12-13 21:41 UTC, ngld requested changes
Thanks a lot. This already looks a lot better than what we had before. I'd like to change just a few small things.

2018-12-13 21:41 UTC, ngld commented on html/templates/kn-page.vue
> +                            <label for="select-installer-file">Select GOG installer file</label>
Placing the `<input type="radio">` tags inside the `<label>`s allows you to drop the `id` and `for` attributes which is much nicer IMO.
Please change the `@click` into a `@change` (if that works, can't check right now). You don't have to click on the radio button to change which one is selected and `@change` catches those events as well.

2018-12-13 21:41 UTC, ngld commented on html/templates/kn-page.vue
> +                        Knossos will copy the files into the Knossos folder.
Not specific to this instance, however, some users seem to be confused by this naming. They don't know what the "Knossos folder" is (the program folder? The `FS2` directory?).  I guess we need a proper name for the data folder (as I've been calling it) and should use that name consistently (the name should be obvious in the first run wizard as well). Any ideas? I'm bad at naming stuff...

2018-12-13 21:41 UTC, ngld commented on html/templates/kn-page.vue
> +                            <input type="text" class="form-control" v-model="retail_data_path" :disabled="retail_searching">
This input field is only visible if the user doesn't want to use auto-detection but is disabled while that's running. We should either make explain why the field is disabled. Something like:
```
:placeholder="retail_install_option === 'auto-detect-installation' && retail_searching ? 'Looking for FS2...' : ''"
```
Or remove the `:disabled` attribute. In the latter case we also need to ensure that the result of the auto detection doesn't overwrite anything the user entered (probably check if `retail_install_option` is `auto-detect-installation` before updating `retail_data_path` in `retailAutoDetect`.

2018-12-13 21:41 UTC, ngld commented on html/templates/kn-settings-page.vue
> +    props: ['mods', 'retailInstallCompleted'],
This seems like a hack. A better solution would be to trigger an event on the settings page once the retail popup is done and reload the settings whenever that event arrives here. After the reload `retail_installed` should be `true` (assuming the retail installation was successful) thus making `retailInstallCompleted` redundant.

Let me know if you want to implement this or if I should take care of it.

2018-12-14 06:42 UTC, jg18 commented on html/templates/kn-page.vue
> +                            <label for="select-installer-file">Select GOG installer file</label>
Ok, will fix in next commit.

2018-12-14 08:09 UTC, jg18 commented
I'll respond to your other comments later, but a couple random thoughts before I head to bed:

- The retail prompt should probably re-mention the "you can buy FS2 on GOG or Steam" line found in the revised welcome page.

- (Out of scope for this PR) The troubleshooting page (PR to revise that likely in the plans, haven't examined it carefully enough yet) should probably include the "need help or have feedback?" section found in the revised welcome page if space allows.

2018-12-15 07:01 UTC, jg18 commented on html/templates/kn-page.vue
> +                        Knossos will copy the files into the Knossos folder.
How about "Knossos library" folder? That's what GOG and Steam call the folder where they stash your games.

2018-12-15 07:11 UTC, jg18 commented on html/templates/kn-page.vue
> +                            <input type="text" class="form-control" v-model="retail_data_path" :disabled="retail_searching">
IMIO hiding the input/browse button when auto-detect is selected is the best thing to do. They're irrelevant while auto-detect is in use and can only cause confusion (or problems for coders 😉). However, I also think space should be reserved for them when hidden so that the controls on the prompt don't jump  around  when you change install options. That's why I used CSS `visibility` isntead of `v-if`. The `disabled` on the input was there before but I think it should just be removed, since it's irrelevant if the input is hidden anyway.

2018-12-15 07:14 UTC, jg18 commented on html/templates/kn-settings-page.vue
> +    props: ['mods', 'retailInstallCompleted'],
And I thought was so clever and doing things The Right Way for passing data from parent component to the child component via a prop. But I'll look into getting an event working.

2018-12-15 07:21 UTC, jg18 commented on html/templates/kn-page.vue
> +                        Knossos will copy the files into the Knossos folder.
Out of scope for this PR but if we go with "library" then maybe the Home tab should be renamed Library. But then that mixes up the tab with the folder?

I was also thinking the Home tab could be named "Play" so that each tab name would be a short verb in my proposed naming scheme of Play, Explore, Develop, and Troubleshoot. But that's a discussion for later...

2018-12-15 08:17 UTC, jg18 commented on html/templates/kn-settings-page.vue
> +    props: ['mods', 'retailInstallCompleted'],
Hmm ok so this is harder than I thought.

I was thinking of having an event `retail-install-completed` (or maybe it should be `retail-status-changed`?) but then the settings page would have to re-retrieve **all** of the settings, or at least that's how it currently checks whether retail is installed, but that seems like a lot of work to update one setting. But having the settings page handle teh event directly without checking the Python code is no better than passing a prop. Not sure what to do here.

2018-12-15 08:27 UTC, jg18 commented
I think I got everything except for what to call the Knossos folder (I'm a fan of "library") and the event thingy.

2018-12-16 18:41 UTC, jg18 commented
I think I now have nearly everything and then some, but I couldn't get the event working and can't figure out what I did wrong 😕 😠

2018-12-16 19:42 UTC, ngld commented
The event is triggered on `<kn-page>` while the listener is attached to a completely different `<div>`. That's why it's not working. You will probably have to attach the listener to the `<kn-settings-page>` element (using `this.$on` in `created` or `beforeMount`), use [`ref`](https://vuejs.org/v2/api/#ref) to get a reference to that in `kn-page.vue` and then call `$emit` on that ref.

I'll take a look and see if I can implement it myself. Once that's done (whoever manages to do it faster 😄 ), I'll merge this PR.

2018-12-17 01:13 UTC, jg18 commented
I tried implementing your suggested approach for the event as well as various re-interpretations of what you said and could not get it to work 😢  so I think I'll have to leave this last part in your capable hands. I *think* part of the problem is that FS2 takes several seconds to install, so that by the time `kn-page.vue` emits the `retail-install-status-changed` even and the `kn-settings-page.vue` receives it, the FS2 install process is not yet complete, so querying `fs2mod.getRetailInstallStatus()` returns false. I wonder if the Python code will have to emit some kind of event after it finishes installing FS2, which will then get connected to `kn-page.vue` and from there to `kn-settings-page.vue`. But that could mean a delay of several seconds from the time the popup closes to the time the settings page is updated, which means the Install FS2 button will stick around for several seconds.

2018-12-17 01:28 UTC, jg18 commented
If I'm right and FS2 installs in the background even after the prompt disappears, does that make sense? How does the player know when they can start playing FS2 mods? Wouldn't it make more sense to put up a "please wait while installing FS2..."-type popup and make them wait a few seconds for the install to either finish or fail?

2018-12-17 20:25 UTC, ngld commented
FS2 is installed in the background. It used to have a progress bar on the bottom (like the update process or the verify file integrity action). That changed at some point and now it's handled the same way mod installations are: FS2 show up on the home tab as soon as the installation is started. The mod tile for FS2 show a progress bar and clicking on "Installing..." opens a popup with further details on the progress.
The welcome page handles this correctly: As soon as `fs2mod.copyRetailData` is called, it switches the popup to display the installation progress. Once the installation finishes (`fs2mod.retailInstalled`), it hides the popup and continues to the next step.

We should probably do the same here (I wouldn't close the popup though). I'd be fine with the settings page being a few seconds delayed (though that probably won't be a problem).

This also simplifies the event passing since we now don't have to emit Vue events from one view to another. Instead we just have `kn-settings` listen for `fs2mod.retailInstalled` and update `retail_installed` each time it's emitted. The event is only fired if the retail installation was successful. Unless there's a bug in some other part of the code, we can assume that retail's installed and set `retail_installed = true`.

2018-12-18 07:28 UTC, jg18 commented
Ok, that sounds good. What about the case where the player installs retail from Explore rather than settings? Should there still be a "please wait"/progress popup? Or just let it install in the backgroudn the way mods/TCs do?

Also since I've run into problems getting events to work, how does one get `kn-settings-page.vue` to listen to `fs2mod.retailInstalled`? Or are you still up for finishing this last piece of the PR?

2018-12-18 19:06 UTC, ngld commented
I'd always display the popup regardless of where the user currently is since the FS2 tile can be easily missed if you're not looking for it.

I can do the event stuff but it's basically
```javascript
created() {
    fs2mod.retailInstalled.connect(this.retailinstallDone);
},

beforeDestroy() {
    fs2mod.retailInstalled.disconnect(this.retailInstallDone);
},

methods: {
    retailInstallDone() {
        this.retail_installed = true;
    }
}
```

This code ensures that the listener is connected when necessary and cleaned up when it isn't.

2018-12-18 19:07 UTC, ngld approved these changes

2018-12-19 07:40 UTC, jg18 commented
Once PR #145 (welcome page) is merged, I'll rebase this branch and update the folder selection part of the prompt to tell people to look for `root_fs2.vp`. Then you can work your event wizardry and this should be good to merge. 🙂

2019-01-02 06:29 UTC, jg18 commented
Hmm, I'll need a little time to merge the manual retail folder selection code in the retail prompt and welcome page to minimize code duplication before I can update this branch. Then you can look into finishing the event/signal handling and popup closing as you described above.

2019-01-07 05:43 UTC, jg18 commented
Ok, assuming you're happy with the latest commit, I guess I can try adding  the event handling in the settings page and the "Installing FS2..." popup based on your comments above and the existing popup code in the welcome page. Then I think this should be good to merge.

2019-01-08 15:20 UTC, jg18 commented
Um I still can't get the event handling or popup to work correctly. 🙁 Connecting the `retailInstallDone` method in the settings page doesn't work and the "Instlaling FS2" popup doesn't quite work right ether. Can I still leave this last part in your capable hands?

2019-02-12 21:24 UTC, merged

2019-02-12 21:26 UTC, ngld commented
Merged. Everything seems to work fine after a18a57bf52e970562aa64ce9a3411b59aceac302.
Once again: Thanks a lot! ^^