Revise Develop(ment) tab
ngld/old-knossos pull request #149
Opened 2018-12-15 21:02 UTC by jg18

*Note*: This is a WIP. I wanted to post what I have so far in case you already have feedback.

To explain why I prefer Develop for the tab name over Development, it's shorter and lines up nicely with the verb theme started by Explore. As mentioned inanother PR, I was gonna propose modifying the tab names so that each one is a (relatively) short verb. But that's up for discussion of course.

Btw why is the create mod popup in both `kn-page.vue` and `kn-devel-page.vue` ? I just realized I was editing the wrong template if I wanted to update that popup. Are any other dev tab popups duplicated like that, just so I know which page to edit?

Also, are the tabs called "tabs" or "pages" in player-facing text? We ran into this same question in wxL and I forget which one we chose, but picking one term and being consistent in player-facing text is important. I'm inclined towards "tab" myself.

2018-12-15 21:15 UTC, jg18 commented
On second thought, maybe the instructions should go back to gray, to make it cleareer it's palceholder text until you have stuff you're working on. Originally I thought it just made the text harder to read for no apparent reason. Opinion?

2018-12-15 21:40 UTC, ngld reviewed
I'm fine with renaming the tab to develop. Heh, I've been calling it "dev tab" for quite some time now.
The create mod popup is only in `kn-page.vue`. The stuff you edited in `kn-devel-page.vue` is the mod details tab. The mod details tab allows you to edit the mod metadata for existing mods while the create mod popup (obviously) creates new mods. It's not great since it's code duplication and I don't like how cramped the create mod popup is. It shouldn't be too hard to fix that; We could show the mod details tab once the user clicks on "Create Mod" and disable all other mod tabs (FSO, -mod flag, etc.) until the mod has been saved. We just have to be careful to initialise all relevant variables and disable immutable fields (like the mod ID and type). Those fields are currently the easiest way to tell the two screens apart.

The tabs are called tabs. However, at this point we have three different tab bars: The top tab bar (home, explore, develop, ...) and two rows for the dev tab: The hard-coded tabs (FSO, -mod flag, staff, ...) and the one tab for each package.

I agree that the gray text is too hard to read. IIRC an older version displayed the text "No mod selected" to indicate that the text below is a placeholder but someone else suggested changing that since it would display a negative message as the first thing to the user or something like that...

2018-12-15 21:40 UTC, ngld commented on html/templates/kn-devel-page.vue
> +                <!-- TODO including a few carefully chosen links to online modding resources might be a good use of space. -->
This would be a good place to link our [mod creation guide](https://docs.google.com/document/d/1oHq1YRc1eXbCgW-NqqKo1-6N_myfZzoBdwZuP16XImA/edit?pli=1) which tries to guide the user through the whole mod release process.
Also, qtFRED (or QtFRED?) is included in the latest nightlies and *should* already show up in Knossos.

2018-12-15 21:40 UTC, ngld commented on html/templates/kn-devel-page.vue
> +                                        A build of the FreeSpace 2 Open (FSO) engine (fs2_open*.exe, fs2_open*.app, etc.)
Why change `AppImage` into `app`? Both are valid so maybe we should just add `app` to the list? In any case, `AppImage´ is the ending for the AppImage binaries that are built for Linux.
There's also a long standing bug with the way Knossos compresses uploads that breaks any mac builds (symlinks aren't packed correctly since `7z` archives don't support them).

2018-12-15 21:40 UTC, ngld commented on html/templates/kn-devel-page.vue
> +                                        A change that overrides, such as custom HUD tables
Both of these types are here since they're part of the original design and I still intend on implementing them. However, right now, they do nothing. The tools and extensions will show up in the list and you *could* upload, install them, etc. but you won't  be able to launch them. We should probably hide these options until they're implemented.

Also, a note on extensions: A prime example would be the cockpit mod. It includes a bunch of files that you would have to add to any mod you want to use it with. My idea is that you can put those files into a single extension and then tell Knossos to launch an installed mod with that extension. For example, you could launch the Cockpit Mod with the MediaVPs or Blue Planet.

2018-12-16 00:01 UTC, jg18 commented on html/templates/kn-devel-page.vue
> +                                        A build of the FreeSpace 2 Open (FSO) engine (fs2_open*.exe, fs2_open*.app, etc.)
Hmm, I guess I hadn't heard of AppImage and was in an editing frenzy or something. I'll put back AppImage and add .app.

As for the Mac upload bug, I think that .dmg (macOS disk image files) are the solution. Take all of the files you want to upload and put them into a .dmg (use compressed .dmg format if you like) and then zip the .dmg into the .7z, kind of analogous to how a tarball puts all of the files in a .tar and then zips the .tar. I think that symlinks would be preserved in that case. There are command line utilities on macOS for creating .dmg files (and probably also for opening them) but I forget what they're called. There may also be Python language bindings for access to this part of the macOS APIs I guess? This does sound kinda messy and a fair bit of work so it'd be good to first manually test whether using a .7z'd .dmg file works and then create a GH issue for it. I have a MacBook Pro and can probably look at it eventually if you can't.

2018-12-16 00:13 UTC, jg18 commented on html/templates/kn-devel-page.vue
> +                                        A change that overrides, such as custom HUD tables
Ok, interesting. I can look into hiding them. Is `v-if="false"` better than just commenting them out?

Also why aren't the MediaVPs an extension rather than a mod? They aren't a new campaign but a collection of (very useful!) whistles and bells.

2018-12-16 01:26 UTC, ngld commented on html/templates/kn-devel-page.vue
> +                                        A build of the FreeSpace 2 Open (FSO) engine (fs2_open*.exe, fs2_open*.app, etc.)
I'd prefer using a `.tar.gz` archive since that can be built with a simple call to `tar -czf ...`. Building DMG files requires measuring used disk space and other fancy stuff. (The tool you're looking for is `hdiutil` IIRC) There is a Python tool that can build dmgs (which I use for the macOS Knossos releases) called `dmgbuild`. However, that's overkill if we can achieve the same using `tar`. Also, building dmgs on anything but macOS is nearly impossible. `tar` already works on macOS, Linux and Windows (if you install it through Cygwin, MSYS2, git4windows, scoop, ...). No idea if `tar` supports symlinks on Windows though...
Either way, the core problem is detecting when we need to do this and aborting with an error if `tar` can't be found. Just looking for symlinks might be a solution.

This is pretty low-priority though since even with all of these changes, most likely only Linux and macOS users would be able to upload FSO builds. The current FSO nightlies are uploaded automatically once the CI compiles them. I'd rather make that script standalone and more flexible so that other people could use it for their own repos (thus also ensuring that we always have macOS and Linux builds).

2018-12-16 01:32 UTC, ngld commented on html/templates/kn-devel-page.vue
> +                                        A change that overrides, such as custom HUD tables
Commenting out is better (saves the template parser some work and makes sure that it's not compiled). I suppose with `v-if="false"` it would get optimized out in release builds but that's not 100% reliable.

As pointed out elsewhere, extensions aren't implemented, yet. They also aren't launchable by themselves (wouldn't make much sense to launch a cockpit mod by itself).
Whether a mod contains a new campaign or replaces the retail campaign doesn't make much of a difference to the launcher so there's no real reason to handle them differently.

2018-12-16 03:20 UTC, jg18 commented on html/templates/kn-devel-page.vue
> +                                        A build of the FreeSpace 2 Open (FSO) engine (fs2_open*.exe, fs2_open*.app, etc.)
Yeah, fair points about preferring tarballs over .dmg and it being low priority anyway.

2018-12-16 18:58 UTC, jg18 commented
Um, how did I break CI?

2018-12-16 19:13 UTC, ngld commented
That was a bug in the CI software. Updated it and everything's fine now.

2018-12-17 20:30 UTC, ngld commented
Looks like this is ready for merging. Anything you want to change before I do that?

2018-12-18 07:44 UTC, jg18 commented
I don't think I revised the help text or commented out the Tool/Extension options in the "create mod" popup yet. I was also hoping to go through more of the mod creation process and see if I have any other thoughts about how to improve the experience Knossos-wise -- was gonna create a (private?) dummy mod for testing called "Awesome Mod" following the adventures of the GTC Awesome or something.

I did notice that if Knossos can't connect to Nebula to verify that your Mod ID is unique, it warns you with a "use at your own risk" QMessageBox popup but there's only an OK button and no way to back out! 😛

2018-12-18 15:31 UTC, jg18 commented
Btw, not sure who owns the Mod Creation Gudie but there *really* should be access controls on editing, probably read-only publicly but write access given only to specific Google accounts. We don't want to open the door to vandalism.

2018-12-18 16:27 UTC, jg18 commented
Also, is it worth including in the `dev-instructions` div links to resources in addition tothe mdo creation guide, like FS Wiki portals on modding or FREDding or things like that? Or maybe there are forum threads worth listing as a resource?

2018-12-22 04:45 UTC, jg18 commented on knossos/runner.py
> +    exes = []
I think this line is needed based on an experiment with the Python interpreter:
```
>>> try:
...     foo = 3
... except Exception:
...     pass
... foo
  File "<stdin>", line 5
    foo
      ^
SyntaxError: invalid syntax
>>> foo = 0
>>> try:
...     foo = 3
... except Exception:
...     pass
...
>>> foo
3
```

2018-12-22 04:53 UTC, jg18 commented
I was wondering why executables are stored in  `selected_pkg` and not `selected_mod`. Aren't exes per-mod and not per-mod package?

Also the user-facing text uses "executable" and "build" interchangeably, which isn't ideal but I guess  the user needs to know/learn that they're synonymous at least when it comes to FSO.

2018-12-22 23:18 UTC, ngld requested changes
Re: Guide links, not sure. Should probably asks actual modders either in the forum thread or on Discord. The guide was initially created by Axem who still owns the document. Will have to ask him if he can make a read-only link or something like that.
Otherwise, I could make a static copy on fsnebula.org and link to that. That means we'd have to manually update it but that also means there's no way to vandalize it.

2018-12-22 23:18 UTC, ngld commented on knossos/runner.py
> +    exes = []
It's certainly more "correct" and nicer. However, in practice it doesn't matter since each of the `except` sections below aborts execution of the function with `return`.
Since you went to the trouble of adding it, we'll leave it in.  :)

2018-12-22 23:18 UTC, ngld commented on html/templates/kn-devel-page.vue
> +                                which might have a main package and optional packages for voice acting or high-detail models.
Important notes here:
* Hard limitation of 2 GiB per package due to limitations of VP files
* Each package is packed into one archive. Knossos doesn't resume failed downloads (it restarts them) so splitting huge packages into smaller ones can help users with a unreliable internet connection.
* During uploading only modified packages are uploaded. If you have a separate package for your missions, updates that only change missions will result in small updates since the models, textures, etc. don't have to be redownloaded. This feature is currently broken though due to a mistake on my part.

These are mostly issues on Knossos side that the user shouldn't have to deal with (even the VP limitation can be worked around by having Knossos build multiple VPs per package in that case). I'm just noting this here since this is already known to a few modders.
Ideally, we should fix these issues instead of teaching people workarounds. That'll take time though. Not sure what the best course of action here is.

2018-12-22 23:18 UTC, ngld commented on html/templates/kn-devel-page.vue
> +                                <!-- Just because the URL says fsnebula doesn't mean we have to call it "FS Nebula". I'm a fan of just calling it "Nebula". -->
I just call it Nebula (unsurprisingly, nebula.org was taken so I had to settle for fsnebula.org). Knossos *should* consistently call it Nebula as well. I'm not entirely shure though.

2018-12-22 23:18 UTC, ngld commented on knossos/runner.py
> +                          ' Make sure you have an FSO build selected on the FSO tab.'))
A huge problem with this is that this can show up for end users as well under certain conditions (I know the original error message isn't much better). However, they won't know which FSO tab you're talking about.

i want to eventually rework the way engine dependencies work by splitting them out of the normal dependencies and storing them directly on the mod object. This will make them a special case but that allows us to handle a bunch of problematic cases much better (like this one).
Until then, checking `mod.dev_mode` is a good way to check whether the user is a dev or not.

Possible reasons this could happen on a normal system / user installation:
* The user is on a 32bit Linux. We only have 64bit Linux builds thus it's impossible to find a matching build. IIRC they won't be able to install mods so they might not come this far. However, if they somehow managed to install a mod (possibly by copying the library folder from a different computer), they'll see this error.
* Dependency issues which will cause Knossos to be unable to find the engine mod (horrible naming, I know).
* Some kind of installation issues with the engine (corrupt / missing files, etc.).

2018-12-23 08:33 UTC, jg18 commented
Thanks for the feedback. I'll work on it during the day (it's after midnight here).


Some admittedly out-of-scope thoughts:

While I was waiting for feedback I tried implementing the sorting menu but the result was a horribly hackish half-working mess. I kept a gist of the changes in case any of it is useful: https://gist.github.com/jg18/735da1690bfd03f292bbf163cdb7ce18

Also, I noticed after installing a few mods that whenever I switch to the Explore tab, there's a 2 second delay before it comes up. Why is that? It's kind of annoying IMHO. I'm guessing it's from having to run `update_mod_list()` every time we switch to Explore? is there a way we can cache the Explore mod data either Vue-side or Python-side and just swap it in while updating HellWindow in the background (e.g., calling `update_mod_list()` without emitting a Qt signal)?

I also noticed this 2-second delay when trying to implement the sorting menu. To make the sorting not so sluggish, IMO we need to optimize this, e.g., by doing the sort JS-side while performing the same sort Python-side (`update_mod_list()`) without emitting a Qt signal.

2018-12-23 20:53 UTC, jg18 commented
As for modding resource links, I'll ask on #freespace on Discord and ask them to PM us on HLP.

As for the Mod Creation Guide, I'm pretty sure Google Docs supports providing a read-only link to a doc while restricting write access to a specified list of Google accounts. IIRC my netcode doc is set up that way. I'll PM Axem and ask him to set up the guide that way.

Will get to your other comments in a bit...

2018-12-24 05:43 UTC, jg18 commented on html/templates/kn-devel-page.vue
> +                                <!-- Just because the URL says fsnebula doesn't mean we have to call it "FS Nebula". I'm a fan of just calling it "Nebula". -->
Ok, in my revisions should I refer to Nebula as just "Nebula"? Or "Nebula mod repository"  (or "Nebula server"?) on first reference and then just "Nebula" after that?

2018-12-24 07:06 UTC, jg18 commented
The latest commits should address everything except getting a read-only link to the mod creation guide (I PMed Axem on HLP about it, waiting for a response) and maybe adding some more resource links. The PR doesn't cover all of the changes I might want to propose but it's a great start. 🙂 

Listening to the Dev Help section with the screen reader uncovered a number of spelling errors 🙁 but at least they're fixed now.

2019-01-01 16:09 UTC, ngld commented on html/templates/kn-devel-page.vue
> +                                <!-- Just because the URL says fsnebula doesn't mean we have to call it "FS Nebula". I'm a fan of just calling it "Nebula". -->
Just Nebula should be fine. We probably need an FAQ for stuff like packages anyway. We can explain what Nebula means there.

2019-01-01 16:15 UTC, ngld approved these changes
Looks good to me. Once the new guide link is in, I'd say we can merge this.

2019-01-01 16:15 UTC, ngld commented on html/templates/kn-devel-page.vue
> +                                <li>Each compressed archive file on Nebula contains a single VP file.<br>
This is only true if the uploader uses Knossos' automatic VP packing. If they manually build VP files and put them in packages, each package (and thus archive) can contain more than one VP file. Not really a problem, rather a nitpicky detail.

2019-01-02 04:27 UTC, jg18 commented on html/templates/kn-devel-page.vue
> +                                <li>Each compressed archive file on Nebula contains a single VP file.<br>
Hmm, I'm a little confused. By "automatic VP packing" you mean the entire process from package folder to VP file to .7z archive file, right? Yeah I suppose that if you create the VP files and then pack the VP files into compressed archive files yourself, you can pack the data however you like. I'll see if I can come up with a succinct way of explaining that. I'm not sure we should encourage people to VPify/compress the data themselves when they might mess it up and Knossos can do it painlessly for them.

2019-01-02 04:54 UTC, jg18 commented
Ok, mod creation guide link is now read-only access. Assuming the text revision in the new commit looks good to you. this PR is good to go. 🙂  Then we can wrap up the retail install prompt PR and then the delta updates and finally the sorting menu.

2019-01-04 20:12 UTC, jg18 commented
Given what Orpheus said on the release thread about need to clarify I can make that text revision before you merge this PR. Can probably commit the change this weekend.

2019-01-11 05:36 UTC, jg18 commented
Ok I came up with some new user-facing messages as per 0rph3u5's recommendation and he said the new messages look good to him. I made a few small revisions while I was at it. Assuming you're happy with all of the changes, I'd say this is ready to merge.

2019-01-29 18:01 UTC, merged

2019-01-29 18:01 UTC, ngld commented
Looks good to me! Thanks for your hard work!