Implement sorting menu
ngld/old-knossos pull request #156
Opened 2018-12-29 01:19 UTC by jg18

**Note**: this is a WIP with a bunch of known issues.

This branch is based on the branch for PR #155 since delta updates for mod list updates are required to get reasonable responsiveness.

I couldn't get the existing sorting menu to work (event listeners wouldn't fire no matter what I did) so I switched to useing popper.js since we already use it in the Home tab. Hope it can be made to work here...

Known issues:
- The "Last Played" option is missing because it doesn't work yet.
- The formatting and styling are all messed up. Presumably fixing this requires the right mix of changes to CSS and popper.js options, but my CSS is kind of weak, so I'd really appreciate help here.
- The CSS is messy, although as mentioned this may be hard for me to fix on my own.
- The sort buttons are only clickable from a small spot on the right edge of the button. Not sure why that is.
- The sorting menu doesn't disappear after you select an option.
- The sorting menu icon button still looks active even after the menu is closed sometimes.
- Switching between Home and Explore tabs causes sorting menu selection to be lost.
- Selected sorting option doesn't persist between Knossos sessions.

2018-12-30 01:06 UTC, jg18 commented
Just noticed that unlike Release or Last Updated, Last Played should provide a total ordering and consequently needs to take time into account, even if the time probably won't be user-facing. I'll work on it...

2018-12-30 08:44 UTC, jg18 commented
Since I wasn't sure if you'd like using "Today"/"Yesterday" for dates in mod details, I made a gist of the changes: https://gist.github.com/jg18/11844ab6af10b53f911db4edaee56111

2019-01-01 17:28 UTC, ngld requested changes
Phew, lots of changes. Looks good overall, although I'm not happy with the way `last_played` is handled. Take a look at `InstalledMod.save` and `InstalledMod.save_user` to get an idea of how existing user-specific stuff is saved. I don't like adding new parameters to `get()` since modifications to the mod data for displaying purposes (or similar stuff) should be handled in the same location where the list is generated since that's usually closer to the related code.

2019-01-01 17:28 UTC, ngld commented on html/templates/kn-details-page.vue
> +                    return Object.assign(JSON.parse(JSON.stringify(mod)), {
`return Object.assign({}, mod, {` would be better here. We don't need a deep copy and having to serialize and deserialize the mod for each UI update *really* isn't ideal. Especially due to the fact that this will be called each time the progress info is updated.

2019-01-01 17:28 UTC, ngld commented on html/templates/kn-details-page.vue
> +                    <!-- TODO: use "Today" or "Yesterday" if applicable, perhaps computed property? or do in Python? -->
If we need relative dates, I'd prefer using a library like moment.js ([Example](http://momentjs.com/docs/#/displaying/fromnow/)).
In general it's better to solve problems like this in JS if possible since the Python <-> JS interface is fairly expensive and always adds an extra layer of complexity.

2019-01-01 17:28 UTC, ngld commented on html/templates/kn-page.vue
> +        tab: 'explore', // FIXME shouldn't this be initialized to 'home'? isn't that what's assumed elsewhere like in center?
Doesn't really matter since it's overwritten on initialisation anyway.

2019-01-01 17:28 UTC, ngld commented on knossos/nebula.py
> +            # DISCUSSME why doesn't last_update appear here? should played?
`last_update` is generated on the server side. Sending it wouldn't make sense.
Also, why would you want to publish when the dev last played their mod?!
Besides it'd always be from the person who last uploaded the mod so... you wouldn't even know who last played it.

2019-01-01 17:28 UTC, ngld commented on knossos/nebula.py
> +            # DISCUSSME why doesn't last_update appear here? should played?
See above.

2019-01-01 17:28 UTC, ngld commented on knossos/repo.py
> +
Please move this whole section inside `InstalledMod.get_user`. `get_user` is supposed to contain user-specific data (which `last_played` obivously is) and moving this section to `InstalledMod` allows you get rid of the ugly hack with `center.installed.query`. Though a much better way to do the same in this location would be
```python
if isinstance(self, InstalledMod):
  last_played = self.last_played
else:
  last_played = None
```
or even `last_played = getattr(self, 'last_played')`.

This module should never contain UI-specific logic (`last_played_display`). That currently happens in `search_mods` and might change in the future (see my comments on #154).

2019-01-01 17:28 UTC, ngld commented on knossos/repo.py
> +            result['last_played_display'] = self.last_played.strftime('%Y-%m-%d') if self.last_played else None
See above.

2019-01-01 17:28 UTC, ngld commented on knossos/repo.py
> +        self.modified = True
I don't like this. `modified` only indicates whether `last_played` was changed although one would expect it to relate to the whole object. Just use `self.save_user()` here.

2019-01-01 17:28 UTC, ngld commented on knossos/runner.py
> +    if not is_tool and not mod.dev_mode:
Why do you exclude dev mods here?

2019-01-01 17:28 UTC, ngld commented on knossos/tasks.py
> +        'last_played': None,
None of the other optional fields are listed here (like `release_thread`). Doesn't make much sense adding `last_played`.

2019-01-01 17:28 UTC, ngld commented on knossos/web.py
> +        runner.run_mod_ex(mod, exe, mod_flag, False)
At this point, you don't know whether this is a mod or a tool, yet you still assume that it's not a tool.

2019-01-02 06:40 UTC, jg18 commented
Thanks for the feedback. Yeah some of these changes (especially the `last_played` stuff) were pretty hackish. I'll work on implementing your requested changes, but first let's get my other PRs in. Then I can interactively rebase this branch against develop (dropping the commits that I copied over from PR #155 ).

2019-01-02 06:45 UTC, jg18 commented
Tangentially, since the `strftime` and `strptime` strings are starting to be duplicated in a number of places I was thinking of adding getter functions in `util` for retrieving them so that they're defined in only one spot. The function for returning `kn_library.json` should probably be moved to `util` as well since I'd think it fits better there than in `center`.

Reminds me also that now that the welcome page changes are in, we need a commit to start adding the `kn_library.json` file to Knossos installs so that the welcome wizard doesn't complain when you select an old library folder as your new library. Would you be up for adding that?

2019-01-14 06:24 UTC, jg18 commented on html/templates/kn-page.vue
> +        tab: 'explore', // FIXME shouldn't this be initialized to 'home'? isn't that what's assumed elsewhere like in center?
When `'explore'` is the initial value, on startup the Explore tab header is briefly highlighted before the highlighting moves to the Home tab header. If the initial value is `'home'` then that doesn't occur. Ultra-tiny nitpickI admit. Opinion?

2019-01-14 06:56 UTC, jg18 commented on knossos/web.py
> +        runner.run_mod_ex(mod, exe, mod_flag, False)
I thought `runModAdvanced()` could only be used for mods which is why I didn't check. Fixed in the latest commit.

2019-01-14 06:58 UTC, jg18 commented on knossos/runner.py
> +    if not is_tool and not mod.dev_mode:
I didn't think running mods that the player is developing as playing them but I guess it is.

2019-01-14 07:00 UTC, jg18 commented on knossos/repo.py
> +        self.modified = True
My original thought was that `modified` could be used for future `InstalledMod` attributes to mark the mod as dirty, but I guess that isn't really needed.

2019-01-14 07:02 UTC, jg18 commented on knossos/nebula.py
> +            # DISCUSSME why doesn't last_update appear here? should played?
Yeah I don't know what I was thinking, probably just part of my clumsily hacking around to get `last_played` working.

2019-01-14 07:02 UTC, jg18 commented on html/templates/kn-details-page.vue
> +                    <!-- TODO: use "Today" or "Yesterday" if applicable, perhaps computed property? or do in Python? -->
The latest commit now uses moment.js. I didn't know that existed. Neat.

2019-01-14 07:07 UTC, jg18 commented
I think the new commit addresses all of your comments. Thanks for the thorough review. Once all of my other PRs are merged, I'll do an interactive rebase of this branch, dropping the commits copied over from `mod-list-delta-update`.

2019-01-29 18:04 UTC, ngld commented on html/templates/kn-page.vue
> +        tab: 'explore', // FIXME shouldn't this be initialized to 'home'? isn't that what's assumed elsewhere like in center?
That's... a good reason to change it. IIRC `explore` used to be the default tab which later changed due to user feedback and the default value here is just a relic. Feel free to change it.

2019-01-29 18:10 UTC, ngld approved these changes

2019-01-29 18:11 UTC, ngld commented
LGTM. Do you want to do the default value change for `tab` here or in one of the other PRs?

2019-05-03 20:11 UTC, merged