Add flag parsing using the new JSON format
ngld/old-knossos pull request #95
Opened 2017-11-24 09:50 UTC by asarium

I encountered an issue with the environment that the executable is
started with. If it only contained the LD_LIBRARY_PATH entry then the
SDL code within FSO didn't work for some reason. If the env parameter
was omitted then it worked properly so I emulated the default value by
copying the existing process environment and then change that in case
any changes are needed at all. This fixed the issue on my system.

This does not use the device enumeration features of the new format yet.

2017-11-24 11:53 UTC, ngld requested changes

2017-11-24 11:53 UTC, ngld commented on knossos/runner.py
> +        p = util.Popen(params, env=env, cwd=base_path, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
You could just use `util.check_output` here. Would make it shorter and keep the debug message.

2017-11-24 11:53 UTC, ngld commented on knossos/settings.py
> +    for type in output_types:
`type` is already defined in Python. Please don't overwrite it!

2017-11-24 11:53 UTC, ngld commented on knossos/settings.py
> +                json_flags = json.loads(output)
Please wrap this in `try ... except` in case the output isn't valid JSON.

2017-11-24 14:12 UTC, asarium commented on knossos/runner.py
> +        p = util.Popen(params, env=env, cwd=base_path, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
I fixed this but retrieving the return code is a bit more complicated this way.

2017-11-24 14:12 UTC, asarium commented on knossos/settings.py
> +    for type in output_types:
Fixed.

2017-11-24 14:12 UTC, asarium commented on knossos/settings.py
> +                json_flags = json.loads(output)
Fixed.

2017-11-25 11:22 UTC, merged

2017-11-25 11:22 UTC, ngld commented
Thanks!